# Generated by Django 4.2 on 2025-04-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_category_post_notification_comment_bookmark"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="otp_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
