# Generated by Django 4.2 on 2025-04-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_user_otp_created_at_alter_user_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("otp", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Pending User",
                "verbose_name_plural": "Pending Users",
            },
        ),
    ]
