# Generated by Django 4.2 on 2025-04-27 04:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_comment_parent_comment_user_alter_comment_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="email",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="name",
        ),
        migrations.AddField(
            model_name="comment",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
