# Generated by Django 4.2 on 2025-04-27 04:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_remove_comment_email_remove_comment_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="reply",
        ),
    ]
