# Generated by Django 4.2 on 2025-05-10 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_comment_likes_alter_post_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlantDisease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="disease_detection/")),
                ("disease_name", models.CharField(max_length=255)),
                ("confidence", models.FloatField()),
                ("description", models.TextField()),
                ("remedies", models.JSONField()),
                ("prevention_tips", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
