# Generated by Django 4.2 on 2025-08-01 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_notification_options_notification_actor_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.FileField(upload_to="post_images/")),
                ("caption", models.CharField(blank=True, max_length=255, null=True)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_images",
                        to="api.post",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Post Images",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
