# Generated by Django 4.2 on 2025-08-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_postimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_google_user",
            field=models.BooleanField(default=False),
        ),
    ]
