# Generated by Django 4.2 on 2025-08-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_user_is_google_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.URLField(blank=True, null=True),
        ),
    ]
