# Generated by Django 4.2 on 2025-05-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlantDiseaseDetection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("image", models.ImageField(upload_to="plant_disease_uploads/")),
                ("result", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
